### PR TITLE
#25 server send file memory error

### PR DESCRIPTION
**Pull request by gammaw**

### CODE REVIEW

**Review by pvj — COMMENTED** [review]
Thanks for the changes. Good solution! 

The PR contains changes that I believe we should discuss and perhaps consider to branch it out from here. Just pragmatic thought if we want to move fast w/ releasing it on the public front-end that shouldn't need to wait until we figure out answer to the following question:

Why did you add `file_url`? Could we maybe use the new solution you wrote for `download_play_file` method on the `listen_play_file` endpoint too, and remove the need for `file_url`? Or if it turns out to be needed then it should make all the way to the db layer I think so we can store it there and add date check to it. 

Both would work in a way where we don't have to generate it on every `view_item` call which is the direction I think we should move towards w/ all assets, audio & images once everything is settled. 

So the download changes are good how about we move forward w/ that? Or would you like to merge both download and listen at once?

**Comment by gammaw** [comment]
> Why did you add file_url? Could we maybe use the new solution you wrote for download_play_file method on the listen_play_file endpoint too, and remove the need for file_url? Or if it turns out to be needed then it should make all the way to the db layer I think so we can store it there and add date check to it.

Good questions. The simple redirect works for download but I don't know if it would work for the listen use case (my understanding was that we need a URL for the listen embed). Yes, I guess file_url would work for download too but why make things complicated. I was also thinking of having file_url in the db but since it's a temporary URL I kept it in the JSON response only.

**Comment by gammaw** [comment]
@pvj please review it again after the latest listen API fix.

**Review by pvj — APPROVED** [review]
Looks good to me~~

**Pull request merged**
