### PR TITLE
#66 cert renewal

### PR DESCRIPTION
**Pull request by gammaw**
Sorry for the chaotic commits, the main commit is this one: https://github.com/mmmnmnm/lahmacun_arcsi/commit/eb1da9bdb757573b937e332eccb8e091c999945e

The gist: added a new service (called `certbot`) ala frontend docker-compose

### CODE REVIEW

**Review by pvj — APPROVED** [review]
Looks good to me. Has it been running on test or should we look at it? Just asking the code is good so merge shouldn't depend on it just curious.

Thanks for also removing the entrypoint.sh!

**Comment by gammaw** [comment]
Thanks for reviewing!

> Looks good to me. Has it been running on test or should we look at it? 

Yes, I tested it somewhere before pushing it (I forgot where exactly, it was long ago). But yes, it should work without further testing.

**Comment by gammaw** [comment]
> Yes, I tested it somewhere before pushing it (I forgot where exactly, it was long ago). But yes, it should work without further testing.

Anyway, I'll test it again on dev.

**Comment by gammaw** [comment]
> Anyway, I'll test it again on dev.

I'm being silly. The branch has been running on dev since many days now :)

Sorry for spamming.

**Pull request merged**
